// Generated by CoffeeScript 1.7.1
(function() {
  var changed, el, element, fixers, i, originals, supportsTouch, _i, _j, _len, _len1;

  this.switchText = function(el, find, replace) {
    var re, textContent;
    textContent = el.innerHTML;
    re = new RegExp(find, "gi");
    if (textContent.match(re)) {
      textContent = textContent.replace(re, replace);
      return el.innerHTML = textContent;
    }
  };

  element = this;

  supportsTouch = 'ontouchstart' in document.createElement('div') || navigator.msMaxTouchPoints;

  fixers = [];

  originals = this.querySelectorAll('[data-' + settings.ignoreFlag + ']');

  for (_i = 0, _len = originals.length; _i < _len; _i++) {
    el = originals[_i];
    fixers.push(el.innerHTML);
  }

  console.log(supportsTouch);

  if (supportsTouch) {
    this.switchText(element, settings.clickText, settings.touchText);
  } else {
    this.switchText(element, settings.touchText, settings.clickText);
  }

  changed = this.querySelectorAll('[data-' + settings.ignoreFlag + ']');

  for (i = _j = 0, _len1 = changed.length; _j < _len1; i = ++_j) {
    el = changed[i];
    el.innerHTML = fixers[i];
  }

}).call(this);
